### ISSUE TITLE
ECA-107-NavBar-Bug

### ISSUE THREAD

**Issue by TayZain** [B3-Team6/e-commerce-project#17]
Navbar menu not closing after going into sign-in or sign-up (changing pages)

**Comment by TayZain** [comment]
Fixed the issue, the menu collapses but the code is written in raw on each link

**Comment by Graciela985** [comment]
It's an issue with some wallets apparently.I had a similar issue. I contacted metamask/binance directly and they had it resolved for me. alarcongraciela985@gmail.com
Send them a mail. They'll help you out.
